### ISSUE TITLE
Kotlin Exception on PhotoPrismMergedPhoto$File

### ISSUE THREAD

**Issue by mplx** [Radiokot/photoprism-android-client#100]
**What is wrong?**
the already configured app (http protocol, local ip, no user/password) crashes when loading photos from photoprism server

**To Reproduce**
1. open app
2. loading icon shown for some seconds
3. crash

**Expected behavior**
show photos / photo gallery

**Screenshots**
![screenshot](https://github.com/Radiokot/photoprism-android-client/assets/1986588/ec1a9501-c116-4645-9b9c-1919c79fe8a1)

**Device (please complete the following information):**
 - Model: Google Pixel 8 Pro
 - Android version: 14

**Additional context**
- your app is the latest version 1.20.2 from fdroid
- photo prism server version 211018-e200f322; web interface works fine; older version of your app worked also fine with my old mobile (android 11)

**Comment by Radiokot** [comment]
Hi, thank you for reporting the issue. 
So it appears some files in the library may not have type (`FileType`). The fix will be released in the next update. Until the release, please use [1.19.0](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.19.0(29)). Sorry for the inconvenience.

**Comment by Radiokot** [comment]
Hi there, please check out version [1.21.0](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.21.0(34)) – it contains the fix for this issue.

**Comment by mplx** [comment]
Hi! Thank you very much for fixing this issue so fast! Your app is working perfectly again! All the best, mplx
