### ISSUE TITLE
Android TV exit from app

### ISSUE THREAD

**Issue by gpopesc** [Radiokot/photoprism-android-client#110]
**What is wrong?**
In google Chromecast 4k, I have installed latest version 1.22. All pictures are displayed fine, including slideshow. When I try to play a video, it throw me out of app without any error. The videos are using Hevc codec and are full hd only.
In my phone,  everything is playing fine, including videos.

**Device (please complete the following information):**
 - Model: Google Chromecast 4k
 - Android tv 12

**Comment by Radiokot** [comment]
Hi. Thank you for reporting. To clarify, does this happen only in slideshow?

**Comment by gpopesc** [comment]
> Hi. Thank you for reporting. To clarify, does this happen only in slideshow?

No, it happened also in previous versions. Actually in slideshow, it comme back to first picture (no exit from app)

**Comment by Radiokot** [comment]
Got it.
I'll keep this issue in mind. Unfortunately, player bugs are challenging for me to fight, as they are highly device dependent and I only have 2 smartphones and a few emulators. The error may as well fix on its own after the next update of the player library.
Anyway, thank you for giving the app a chance. "Watch" the repository to get notified on the next release 😉

**Comment by Radiokot** [comment]
Please, try [the latest release](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.23.0(36)). It has the player library updated, which may fix your problem with TV playback.

**Comment by gpopesc** [comment]
Yes, now it is working great
Thank you very much.
