### ISSUE TITLE
Pinch-to-zoom doesn't work as expected

### ISSUE THREAD

**Issue by Radiokot** [Radiokot/photoprism-android-client#118]
### Discussed in https://github.com/Radiokot/photoprism-android-client/discussions/117

<div type='discussions-op-text'>

<sup>Originally posted by **dronnikovigor** January  9, 2024</sup>
When i open photo and try to zoom with 2-finger-gestue it just moves the photo. The only way is to zoom with double tap. And then you can use pinch-to-zoom. Sometimes it's not so convinient. </div>

https://github.com/Radiokot/photoprism-android-client/assets/4175117/25254f3b-34ad-4036-a31a-380cd18928a3

**Comment by Radiokot** [comment]
@ippocratis @dronnikovigor hey guys, I've made some fixes to the swipe dismiss gesture in [1.30.0](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.30.0(45)), this should improve the zooming. Please, try this version.

**Comment by ippocratis** [comment]
Pinch to zoom works nicely.
