### ISSUE TITLE
unconverted raw files are shown in the gallery

### ISSUE THREAD

**Issue by alberteuz** [Radiokot/photoprism-android-client#123]
**What is wrong?**
It's not much of a big, but it's an annoying feature. In my gallery, along with jpegs unconverted raw files are displayed. On the web app they are not present.

**To Reproduce**
1. Import folders that contain both raw and jpeg files
2. Do not convert raws
3. In the gallery app, raw files will be displayed as a "blank" image, while in the web app they won't be displaued

**Expected behavior**
Unconverted raw files should be ignored

**Screenshots**
![Screenshot_20240201-110033](https://github.com/Radiokot/photoprism-android-client/assets/158458576/0d6701c9-d1db-40eb-9378-b8ac3831550e)

**Device (please complete the following information):**
 - Model: Fairphone 4
 - Android version: 13

Thank you for your attention and your fantastic app!

**Comment by Radiokot** [comment]
Hello, Alberto. Can you please send me an example of an unconverted RAW and the corresponding JPEG? There are RAWs on the demo site, but it seems like there are no issues with those.

**Comment by alberteuz** [comment]
Hello Oleg,
thank you very much for the quick reply. I don't have a problem with the
RAW conversion, I only want unconverted RAW not to be displayed.
For example, here's a screenshot of my photoprism library from the webapp,
and beside it the same library from my gallery app:

[image: Senza titolo.jpg][image: Senza titolo-1.jpg]

As you can see, only jpegs are displayed in the photoprism web app, while
unconverted raw files are visible as grey boxes in the app.
I had some raw files that were converted and they are displayed correctly:
[image: Senza titolo.jpg]

So the problem is not with conversion or raw files or with them being
displayed, but with unconverted raw files being displayed.
I know it's not a common problem, but it could be useful, as there is a
PHOTOPRISM_DISABLE_RAW flag.
Thank you very much for your help.
Have a nice day
Matteo




Il giorno gio 1 feb 2024 alle ore 14:22 Oleg Koretsky <
***@***.***> ha scritto:

**Comment by Radiokot** [comment]
Matteo, I'm sorry I mistook you for Alberto.
Thank you for more detailed explanation. Will try to reproduce this at home. I agree that it some files have to preview due to disabled conversion, then they shouldn't be shown in the gallery.

**Comment by alberteuz** [comment]
Don't worry, everybody mistakes me for Alberto :)
Thank you again for your kindness!
Matteo

Il giorno gio 1 feb 2024 alle ore 16:26 Oleg Koretsky <
***@***.***> ha scritto:

**Comment by Radiokot** [comment]
I can't reproduce this behavior on my server.
If I set `PHOTOPRISM_DISABLE_RAW`, then the RAWs are not indexed at all – expected result for this flag;
If I set `PHOTOPRISM_DISABLE_RAWTHERAPEE`, then the RAWs are indexed and get JPEG thumbnails, hence they are visible in both the web app and the gallery.

Maybe your thumbnail cache is corrupted?

**Comment by alberteuz** [comment]
Oh ok, I will check on that, it's probably this.
Thank you very much anyway!
Best regards
