### ISSUE TITLE
Downloading or sharing stuck

### ISSUE THREAD

**Issue by krair** [Radiokot/photoprism-android-client#127]
**What is wrong?**
When clicking either the download or share button, the progress bar or icon at the bottom will continue to "spin" but never actually complete.

I can see the data is pulled to the device (by a network speed indicator), but then never finishes the process. If I click to the side to exit the download status pop-up, nothing has happened. There is no photo downloaded anywhere on the device

**To Reproduce**
1. Go to any photo.
2. Click download or share.

**Expected behavior**
The photo is downloaded to the device.

**Screenshots**
I can add if needed but there isn't anything to show.

**Device (please complete the following information):**
 - Model: Asus Zenfone 8 and a Huawei p20 lite
 - Android version: 13 and 9

**Additional context**
Version 1.23.0 from fdroid.

**Comment by Radiokot** [comment]
Hi there.
I've faced such behavior on PhotoPrism public demo and fixed it. The update will be published very soon. F-Droid, as always, will take week or two to publish the new version. I'll let you know once the APK is available on GitHub.

**Comment by Radiokot** [comment]
Please, check out the latest release:
https://github.com/Radiokot/photoprism-android-client/releases/tag/1.24.0(37)
