### ISSUE TITLE
Offline mode [feature request]

### ISSUE THREAD

**Issue by ippocratis** [Radiokot/photoprism-android-client#13]
Being able to navigate a bit in the app
while it is indeed snapy I think it suffers from  on of the basic disadvantages the pwa do
There is no offline mode
Being a proper android app maybe there is a way to cache the alreafy cahed thumbnails and photos/videos for ofline view
to take it even further an option to predownload all thumbnails would also probably make sense for even faster scrolling thumbnail loads

Example app that does the same (the pre-caching). 
It is a Kotlin android client for another popular photo managment app librephotos https://github.com/savvasdalkitsis/uhuruphotos-android/commit/ebd77b0aa49c7b3181c6a0524b383a8f82f85e0a

On the other hand I'm not sure this is even doable with web service api (or maybe it is totaly indipended from the api?)

Thanks
keep up

**Comment by ippocratis** [comment]
Moving this to discussion as its more appropriate

**Comment by meonkeys** [comment]
https://github.com/Radiokot/photoprism-android-client/discussions/16
