### ISSUE TITLE
Authelia redirection not working

### ISSUE THREAD

**Issue by BapRx** [Radiokot/photoprism-android-client#131]
**What is wrong?**
Hi thank you for this app, while looking at the latest release I realized that Authelia should now be supported but I don't get redirected to the auth portal.

**To Reproduce**
I reset the app then tried to log in using the base URL but no redirection happens, the app just reports the 401 error.

**Expected behavior**
The web browser opening to the auth portal.

**Screenshots**
![share_3316446001017637086.jpeg](https://github.com/Radiokot/photoprism-android-client/assets/32563450/909574d0-6160-4a93-9e59-5459c1d76fa9)

**Device (please complete the following information):**
 - Pixel 6 pro
 - Android version: 14

**Additional context**
Logs from the Authelia server:
```log
authelia-wzgxp authelia time="2024-03-03T17:59:20+01:00" level=info msg="Access to https://photos.example.com/api/v1/session (method POST) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://auth.example.com/?rd=https%3A%2F%2Fphotos.example.com%2Fapi%2Fv1%2Fsession&rm=POST" method=GET path=/api/verify remote_ip=1.2.3.4
```

**Comment by Radiokot** [comment]
Hey there Baptiste. 
Is this a standard behavior for Authelia? I don't have it personally, but we've tested the redirect with another PhotoPrism Gallery user who has their library under Authelia.

**Comment by Radiokot** [comment]
For now, I can suggest configuring Authelia to make redirects for your PhotoPrism library using HTTP codes in the 300 range – redirects by 401 with `Location` is not supported by the app's network stack.

**Comment by BapRx** [comment]
I haven't altered the default response behavior of Authelia and it seems to respond with a 3XX code for `GET` / `OPTION` requests per the [documentation](https://github.com/authelia/authelia/blob/b9f995ca53f5315664445948e2621097e1cbda86/docs/content/en/integration/proxies/introduction.md#response-statuses): 

If I understand correctly, Authelia returns a 401 with the header [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) set, since it's a standard maybe the app could catch this?

**Comment by Radiokot** [comment]
Hmm, I think I got what's wrong. You use PhotoPrism credentials along with Authelia while the one who tested this feature had their libarary running in a public mode to avoid double authentication. If you connect to a public library, the first request is GET, however, if there are credentials, it is POST. That's why Authelia responds differently.
Question out of curiosity, why would one want to have 2 authentications one by one for a photo library?

**Comment by Radiokot** [comment]
Please, try connecting to he library with Authelia and PhotoPrism credentials in this build:
https://send.bitwarden.com/#_hYd9lj5D02iKrEoAUNrwg/YV-QviPYcFXbDxNcICmKyg

**Comment by BapRx** [comment]
> Hmm, I think I got what's wrong. You use PhotoPrism credentials along with Authelia while the one who tested this feature had their libarary running in a public mode to avoid double authentication. If you connect to a public library, the first request is GET, however, if there are credentials, it is POST. That's why Authelia responds differently. Question out of curiosity: why would one want to have 2 authentications one by one for a photo library?

Good analysis! I'm indeed running an authenticated Photoprism instance mostly because I'm synchronizing pictures from my devices with an app that doesn't support Authelia and thus I have to bypass the 2nd factor for this specific route. I still want it to be password protected.

Also I'm waiting on these issues to be completed since it's imo the optimal setup https://github.com/photoprism/photoprism/issues/782 / https://github.com/photoprism/photoprism/issues/3943

I just tested the APK you sent me and it's working! Good job and thank you for you reactivity.

Tell me if you need any more test or information.

**Comment by Radiokot** [comment]
Makes sense indeed 💡 
Thank you for testing, the fix will be included into the next release. Until then, you can use the clone build if you are comfortable with it.

**Comment by BapRx** [comment]
Perfect thank you 🎉
