### ISSUE TITLE
分屏时工具栏不显示

### ISSUE THREAD

**Issue by JinbiaoXiong** [Radiokot/photoprism-android-client#132]
**What is wrong?**
分屏时，不论APP在上面或者在下方，工具栏都不会显示。不使用分屏，独占屏幕后工具栏显示。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Model: [e.g. Redmi Note 12]
 - Android version: [e.g. 14]

**Additional context**

**Comment by Radiokot** [comment]
Hi. Please, send screenshots.
