### ISSUE TITLE
去哪里找客户端证书？

### ISSUE THREAD

**Issue by mygit20230606** [Radiokot/photoprism-android-client#134]
👉🏻 [Start discussing an idea](https://github.com/Radiokot/photoprism-android-client/discussions/new?category=ideas)
这个客户端证书指什么   是我加密https用的证书 还是什么？

**Comment by Radiokot** [comment]
It is for mTLS, you probably don't need it.

**Comment by mygit20230606** [comment]
> It is for mTLS, you probably don't need it.这是mTLS，你可能不需要它。

我需要的  我的服务端用的nginx+https   我这里的cert.pem是不是需要使用nginx的

**Comment by Radiokot** [comment]
If you use custom certificates for your environment, make sure to install the CA certificate on your phone. Android won't let you connect to a server with a certificate signed by an unknown authority.

**Comment by mygit20230606** [comment]
> If you use custom certificates for your environment, make sure to install the CA certificate on your phone. Android won't let you connect to a server with a certificate signed by an unknown authority.

谢谢大佬！已经整好了  太喜欢这个作品了！加油
