### ISSUE TITLE
Random long loading times 

### ISSUE THREAD

**Issue by Blendan1** [Radiokot/photoprism-android-client#146]
**What is wrong?**
Some images take very long to load and when sharing they won't download and just get stuck.
Also half the time when opening it won't load and I have to close the app and reopen before it loads.

I checked my internet connection, server usage and checked the website directly when it was not loading and nothing was looking off.

WiFi or not doesn't make a difference.

Is there a way so view/share a log from the app? Maybe that would help.

**Device:**
 - Model: Pixel 6
 - Android version: 14
- Photoprism: 240420-ef5f14bc4

**Comment by Radiokot** [comment]
Hi. This is weird, we'll try to figure it out.

1. When you say "half the time when opening it won't load", you mean the gallery grid doesn't load at all, or particular photos?
2. Do you have dynamic previews enabled in your library advanced settings (in the web app)?
3. What's your static preview size limit?

**Comment by Blendan1** [comment]
1. I just activated the extension and now the grid loads every time, but is always slow (when using the PWA it's almost instantaneous).
Same for some images, I couldn't find anything that they have in common.

2. No it's disabled 

3. 2048px should I try reducing it?

**Comment by Radiokot** [comment]
Thanks, your library preferences seem fine.
Is the loading this slow when connected to a demo library as well? Please, try https://demo.photoprism.app

**Comment by Blendan1** [comment]
The dome library works without issues, sorry I should have checked that before.

But I'm still confused as the PWA is working without issues too.

**Comment by Radiokot** [comment]
1. Perhaps you have some rate limiter set in front of PhotoPrism which could throttle app requests? 
2. What kind of auth do you use with your library?

**Comment by Blendan1** [comment]
1. I couldn't find an option that would do that the only thing I found is rate limiting for failed logins (but that is for the IP address and I can still load via pwa so it's unlikely that this is the issue 

2.. I'm just using username and password

**Comment by Radiokot** [comment]
Okay, let me think about it through the day. 
I'm so sorry you have gallery connection issues with your setup. If this is not resolved in a short time – I'll refund your money

**Comment by Radiokot** [comment]
What server is your library running on? If it is in your LAN, can you please try connecting the gallery to it by direct IP address (and through HTTP probably)? So we can check if it has something to do with DNS.

**Comment by Blendan1** [comment]
So I tried a couple of things:

Directly over IP: working 
Port forwarding over IP: working 
Port forwarding over address: not working 
Forwarding over ngix: not working 
Forwarding over ngix without tsl: not working 


It seems like the issue might be on my side, but as I said before I'm confused why the PWA is working without issues.

As for the money back: please keep it I have been very happy with your app and appreciate your work. You're also taking time out of your day to help me here so I wouldn't feel comfortable with getting my money back.

**Comment by Blendan1** [comment]
I'm now just directly connecting over the IP and I'm using a VPN to connect to my home network. This solves the issue for me, but if there's something else I could do or an update to the app that could fix the issue that would be very much appreciated

**Comment by Radiokot** [comment]
It may be related to DNS or TLS. Browsers often have their own implementation for this, while regular apps like the gallery depend on the OS defaults. If it's okay with you, can you please email me your library hostname, so I can make some checks on my own?

**Comment by Blendan1** [comment]
I just realised that the same long loading times also happen in the PhotoSync app, didn't see it before because it was syncing in the background.

Maybe it's an android issue, I will look if there's anything to update and report back if the next update fixed the bug

**Comment by Radiokot** [comment]
Interesting

**Comment by Blendan1** [comment]
I recently saw that cloudflare was being DDOSed and now that it's over this issue has been resolved, I'm very sorry for bothering you with it

**Comment by Radiokot** [comment]
Was your public hostname dependent on Cloudflare?
