### ISSUE TITLE
Odd translation of "year ago" into German (Memories-Extension)

### ISSUE THREAD

**Issue by monnypython** [Radiokot/photoprism-android-client#149]
**What is wrong?**
The translation "Year Ago" into German as "Vor Jahr" sounds a bit odd from a German perspective.

**To Reproduce**
1. Go to Startpage of "Photoprism Galerie"
2. Look at the tags of the top row of the memories-cards.

**Expected behavior**
"Year Ago" should be "Vor **1** Jahr". In my opinion, that sounds much better. ;)

**Screenshots**
![image](https://github.com/user-attachments/assets/94a18c45-d8a9-4424-89a4-3754254f4181)

**Device (please complete the following information):**
 - Model: Google Pixel 4a
 - Android version: 13

**Additional context**
-

**Comment by Radiokot** [comment]
Hi. Thank you for pointing that out, I use Deepl and Bing AI to translate strings and sometimes the result is odd. This will be fixed in the next update. Meanwhile, if you find more incorrect strings, please point them out here in the comments 😊
