### ISSUE TITLE
Memory not deleted after deleting the photo

### ISSUE THREAD

**Issue by BapRx** [Radiokot/photoprism-android-client#152]
**What is wrong?**
When deleting a photo which is displayed in the memory section, the thumbnail isn't removed and we cannot expand the photo either.

**To Reproduce**
1. Open any memory photo
2. Delete it
3. Try expanding the photo again

**Expected behavior**
The memory tile should be removed if the selected picture doesn't exist anymore.

**Comment by Radiokot** [comment]
Good evening, Baptiste. I'm sorry that the app brought some moments from the past you'd rather not recall. It's been happening to me too 😟 
I've changed my perspective on it – regardless of how you feel about the thing currently, it is nevertheless a reminder that back then you were happy and involved enough to capture this moment. Or else, if it was something you regret or are ashamed of, then what your current feeling is a sign of your personal growth. One way or another, there is a benefit in seeing such memories 🙂

**Comment by Radiokot** [comment]
Anyway, what if I add the ability to delete a particular memory manually? Like by long-pressing it? Could this be an acceptable solution?

**Comment by BapRx** [comment]
Good evening Oleg, no worries at all!
Are you saying that it's expected to see memories from deleted pictures?

I might have not explained well enough but I'm talking about pictures deleted from photoprism entirely. The issue is when said picture was removed after the memory tile is displayed.

In my opinion a deleted photo couldn't even be displayed as a memory in the first place and so if a memory's underlying picture is deleted, the memory should be removed as well.

What do you think?

**Comment by Radiokot** [comment]
Memories found in the morning are stored in the local database, the record contains the thumbnail URL and the set of photo UIDs to be shown. The gallery doesn't check at each launch if the photos in memories still exist in your library. I don't want to implement this check to not spam the server with queries on app start, therefore I suggest adding the ability to remove a memory manually

**Comment by BapRx** [comment]
I understand, a manual deletion option would be fine with me. Another idea would be to only check if the currently indexed memories still point to existing images.
Either option is good, thank you!

**Comment by BapRx** [comment]
Hello, I see it's been implemented thank you 😊
