### ISSUE TITLE
Files don't upload, even on a working server....

### ISSUE THREAD

**Issue by RefinedTheMite** [Radiokot/photoprism-android-client#154]
**What is wrong?**

**To Reproduce**
1. Go to share a file and use 'import' upload it to you gallery.
2. Click on Set the parameters you want.
4. See error 'Upload Failed' in action centre.

**Expected behavior**
No error should work flawlessly the library I used to test is setup correctly and uses photosync to sync my photos from my phone so WebDAV put does work...

**Screenshots**

**Device (please complete the following information):**
 - Model: POCO (Xiaomi) M4 Pro 4G
 - Android version: 13

**Additional context**
Add any other cont

**Comment by Radiokot** [comment]
Have you tried it on demo.photoprism.app?

**Comment by Radiokot** [comment]
The gallery doesn't use WebDAV, it uses the upload endpoint provided by PhotoPrism, which may be blocked or limited by size in your setup.
