### ISSUE TITLE
Login not working if Photoprism uses OpenID Connect

### ISSUE THREAD

**Issue by sseide** [Radiokot/photoprism-android-client#158]
**What is wrong?**
With current Photoprism versions (since version 240711) Login via OpenID Connect flow is possible.
Here you can use another OIDC provider to do authentication of users as needed. Therefor "normal"
user login does not work anymore.

https://docs.photoprism.app/getting-started/advanced/openid-connect/

To allow access for other apps (e.g. Photosync tested and working) i created an App specific password for my user (Settings -> Account -> App+Device Password).

https://docs.photoprism.app/user-guide/settings/account/#apps-and-devices

This App password is working fine with e.g. Photosync App to access all images.

The same user/password does not work with your App, it always says wrong password.

Trying to insert the URL only without username/password as suggested in the help page does not work too.
It just says 401 Authentication needed. This is kinda expected as the Login page does not redirect to the OIDC provider by itself but just presents a button to go to the OIDC provider instead of a local login.
Local Login is available also in parallel to OIDC.

**To Reproduce**

1. Configure a OIDC provider and Photoprism to use this provider. Started Photoprism with this env vars:
  ```
PHOTOPRISM_AUTH_MODE: "password"
PHOTOPRISM_OIDC_CLIENT: "abc..."
PHOTOPRISM_OIDC_SECRET: "def..."
PHOTOPRISM_OIDC_REDIRECT: "false"
PHOTOPRISM_OIDC_PROVIDER: "Nextcloud"
PHOTOPRISM_OIDC_URI: "https://nextcloud.my.server"
PHOTOPRISM_OIDC_USERNAME: "email"
PHOTOPRISM_OIDC_REGISTER: "true"
PHOTOPRISM_OIDC_WEBDAV: "true"
```
2. Start Photoprism Gallerie
3. Add new Account to Photoprism (official internet facing Url with HTTPS)
4. Enter URL only and pres "Connect"
5. Error "Sammlung benötigt Zugangsdaten" (needs account credentials)

6. Web-Login to Photoprism and create App specific password (Settings -> Account -> App+Device Passwords -> Add)
7. Enter URL + Username + App-Specific Password from 6.
8. Error "Password is wrong"

**Expected behavior**

After creation of an App-Specific password in Photoprism and using this in the Conenction details i
expect Gallerie app to log into the server.

**Screenshots**

**Device (please complete the following information):**
 - Model: Asus Zenfone
 - Android version: 14

**Additional context**

Thanks for looking into it.

**Comment by Radiokot** [comment]
Hi, did you add the app password with the "Full access" level? Did you use it with the "admin" username when trying to connect the gallery?

**Comment by sseide** [comment]
Hi, no - app password was created with WebDAV access level. I created it first for photosync to check. Will try tomorrow with full access level and report back. Thanks

**Comment by Radiokot** [comment]
The gallery is not a WebDAV client, it uses PhotoPrism API to provide rich functionality. It needs full access.

**Comment by sseide** [comment]
Yes - tested with new App-Password with Full Access and its working now. Thanks.

I would suggest to update the documentation regarding Connection data with this information. Currently there is no mention of the App/Device passwords and Access level needed. Only basic things and special SSO case with Login redirect.

Thanks a lot.

**Comment by Radiokot** [comment]
Good point, I'll update the docs.
