### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Radiokot/photoprism-android-client#28]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4160352976#L866

Already tried with Java17, but no joy

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1f168c80713e8a65c647bb55b0691517abd05da7

Diff log between [CI apk](https://gitlab.com/fdroid/fdroiddata/-/jobs/4160352976/artifacts/file/tmp/ua.com.radiokot.photoprism_9.apk) and [upstream apk](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.5.1(9)): [prism1.log](https://github.com/Radiokot/photoprism-android-client/files/11309964/prism1.log)

**Comment by licaon-kter** [comment]
@linsui would the [baseline fix](https://f-droid.org/docs/Reproducible_Builds/#potential-sources-of-unreproducible-builds) help?

**Comment by linsui** [comment]
No, I thought not.

**Comment by licaon-kter** [comment]
Indeed it has, https://github.com/Radiokot/photoprism-android-client/blob/main/app/build.gradle#L142 :)

**Comment by licaon-kter** [comment]
Oh wow, what the...
https://monitor.f-droid.org/builds/log/ua.com.radiokot.photoprism/9#site-footer

:(

**Comment by Radiokot** [comment]
Strange. I don't know what is going on. I've added the following directive for native libraries in case this is what causing failed F-Droid builds. Will see in the next release :)
```gradle
packagingOptions {
    doNotStrip '**/*.so'
}
```

**Comment by Radiokot** [comment]
Come on! 🙄
https://gitlab.com/fdroid/fdroiddata/-/jobs/4167602794

**Comment by licaon-kter** [comment]
For version 9 it does not matter, it verified once so that will be published.

But... an odd issue anyway :(

**Comment by ippocratis** [comment]
Fdroid does not worth the amount of time the devs need to spend to make their apps compatible in my opinion

GitHub releases is more than enough

And google play to expand the userbase

**Comment by Radiokot** [comment]
> Fdroid does not worth the amount of time the devs need to spend to make their apps compatible in my opinion

I really appreciate the overall idea and principles of F-Droid and I think if you develop an app which in some way brings more freedom, it worth tweaking the build to get in on the repository. 
Once the app is in the repo, anyone interested in the most recent version can go to the GitHub releases from the app page, so here I agree that if something is weirdly wrong with the build, it is not a burning issue.

**Comment by licaon-kter** [comment]
@ippocratis as long as you understand that stuff like Obtainium does not install open source apps but random APKs (Signal? apkmirror? lol), use it as you see fit.

F-Droid is not _"just an APK hoster"_.

**Comment by ippocratis** [comment]
> @ippocratis as long as you understand that stuff like Obtainium does not install open source apps but random APKs (Signal? apkmirror? lol), use it as you see fit.
> 
> F-Droid is not _"just an APK hoster"_.

The way I see it (or we users in general see it) is irrelevant .
What Oleg want for his app isnwhat matters.
Fdroid as an appstore is an interesting topic though but not fit in here
I'd be happy to make it over to disqussions maybe?

**Comment by Radiokot** [comment]
Well see how the next release performs. @licaon-kter , thank you very much for taking care 🙌

**Comment by licaon-kter** [comment]
https://gitlab.com/fdroid/fdroiddata/-/commit/53d77bd05c320afc00cfaa190bdf02b71434a473

**Comment by Radiokot** [comment]
Damn...

**Comment by licaon-kter** [comment]
and https://gitlab.com/fdroid/fdroiddata/-/commit/1ddecc8aad29e29db4bbc1a240d21d11afdbc67f#note_1376203213

**Comment by Radiokot** [comment]
Could it be that I build the release APK with JDK 11 while the CI uses version 17 and gets slightly different bytecode?

**Comment by linsui** [comment]
With jdk 11 the diff is

```
│ │ ├── ua/com/radiokot/photoprism/features/gallery/logic/JsonSearchBookmarksBackup.class
│ │ │ ├── procyon -ec {}
│ │ │ │┄ error from `procyon -ec {}`:
│ │ │ │┄ Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/nix/store/42qjpff7h6gb8hxnw0n2vki2833g9v9m-home
│ │ │ │ @@ -76,12 +76,12 @@
│ │ │ │          throw new UnsupportedVersionException(Integer.valueOf(version));
│ │ │ │      }
│ │ │ │      
│ │ │ │      public void writeBackup(final List list, final OutputStream outputStream) {
│ │ │ │          Intrinsics.checkNotNullParameter((Object)list, "bookmarks");
│ │ │ │          Intrinsics.checkNotNullParameter((Object)outputStream, "output");
│ │ │ │          final ObjectMapper jsonObjectMapper = this.jsonObjectMapper;
│ │ │ │ -        final JsonNode valueToTree = jsonObjectMapper.valueToTree((Object)this.createBackupData(list));
│ │ │ │ +        final JsonNode valueToTree = this.jsonObjectMapper.valueToTree((Object)this.createBackupData(list));
│ │ │ │          Intrinsics.checkNotNullExpressionValue((Object)valueToTree, "jsonObjectMapper.valueTo\u2026ateBackupData(bookmarks))");
│ │ │ │          jsonObjectMapper.writeValue(outputStream, (Object)new JsonSearchBookmarksBackup$BookmarksBackup(1, valueToTree));
│ │ │ │      }
│ │ │ │  }
```

Maybe we can try jdk 17 on both side?

**Comment by Radiokot** [comment]
Hmm, the difference is in the same method 🤔
I'll build the next release with JDK 17, meanwhile will try to play around with the method

**Comment by linsui** [comment]
Could you  build it with jdk 17 and upload it here so that we can check the apk?

**Comment by licaon-kter** [comment]
@linsui you bumped it to 17 trying to fix past fails?

**Comment by linsui** [comment]
I guess so.

**Comment by Radiokot** [comment]
@linsui I've attached the JDK17-built file to the latest release:
https://github.com/Radiokot/photoprism-android-client/releases/tag/1.6.0(12)

**Comment by licaon-kter** [comment]
Building with Java11 does not fix the classes diffs for me locally

**Comment by linsui** [comment]
It's the same as your jdk 11 build.

Our jdk 11 build is in https://gitlab.com/linsui/fdroiddata/-/jobs/4218000397/artifacts/file/tmp/ua.com.radiokot.photoprism_12.apk. @licaon-kter Is this the same as your jdk 17 build?

**Comment by licaon-kter** [comment]
The hosted apks are the same, @radiokot you've mixed them up or they are truly repro between 11 and 17?

**Comment by Radiokot** [comment]
I don't know :( I specified the JDK in the Android Studio Gradle settings

**Comment by Radiokot** [comment]
I've just tried to build a release APK with OpenJDK 11.0.2 using `assembleRelease` task with my signature, still in the bytecode I have the line
`invoke-virtual {v2, p1}, Lcom/fasterxml/jackson/databind/ObjectMapper;->valueToTree(Ljava/lang/Object;)Lcom/fasterxml/jackson/databind/JsonNode;`
instead of
`invoke-virtual {v0, p1}, Lcom/fasterxml/jackson/databind/ObjectMapper;->valueToTree(Ljava/lang/Object;)Lcom/fasterxml/jackson/databind/JsonNode;`

Looks like a magic. Maybe I should rearrange the code of this method and explicitly call `this.jsonObjectMapper` without the compiler assigning it's value to a local variable

**Comment by Radiokot** [comment]
Hey guys, please try the new release https://github.com/Radiokot/photoprism-android-client/releases/tag/1.7.0(13)

**Comment by linsui** [comment]
It works and the new version is already built in the buildserver. https://monitor.f-droid.org/builds/log/ua.com.radiokot.photoprism/13#site-footer Thanks!
