### ISSUE TITLE
Cannot download video

### ISSUE THREAD

**Issue by jd1** [Radiokot/photoprism-android-client#4]
Hi, first of All thanks for this awesome app. I really like the native Integration into Android and I'm looking forward to see more features coming!

I noticed that I'm not able to download videos. If I open a video, the app opens the preview image and if I click on the download button, it opens a dialogs "select media file" where I can choose the preview image or the video, but I can't click on anything.

**Comment by jd1** [comment]
I'm using version 1.0.1 and this also happens for the other two buttons: Share and open with another app.

**Comment by Radiokot** [comment]
Hi. That's interesting, I'll check the code. It happens only for videos? Do you have photos with multiple files to try?

**Comment by jd1** [comment]
The same happens to stacked photos and for gifs. It looks like the dialog for multiple files is broken.

**Comment by Radiokot** [comment]
I've managed to reproduce the issue, working on it.

**Comment by Radiokot** [comment]
Please check the 1.0.2: https://github.com/Radiokot/photoprism-android-client/releases/tag/1.0.2(3)
No need to re-install or clean the data.

**Comment by jd1** [comment]
The dialog is working now. Thanks for the quick fix!
