### ISSUE TITLE
HTTPS not working 

### ISSUE THREAD

**Issue by ally9696** [Radiokot/photoprism-android-client#45]
Trust anchor for certification path not found

This error occurs when trying to use HTTPS secured url 

1) But if I use https://demo.photoprism.app it works without error and logged in without error.

2) And later i logout the demo photoprism and I try my personal cloud storage it logins successful and entire personal gallery loads without error.

3)once I close the App from task manager and again i open the APP it gives error "trust anchor for certification not found"

Clearing data and trying to login to personal cloud it gives same issue.

4) To solve it temporarily i have to logout my cloud storage and repeat step 1) and 2) and it solves the issue until i close the app from task manager and the app gives same error for HTTPS.

I tried the PKCS12 client certificate its same issue with and without the certificate its no difference.

My HTTPS is provided from Letsencrypt and web version is working fine on chrome browser.

Login Demo > logout Demo > Personal Cloud login >

**Comment by Radiokot** [comment]
Hi.
I'm sorry you have this weird issue. We'll try to figure it out.
I, too, use Let's Encrypt certificate for test environment running behind nginx and it works fine. The error is specific to your setup, it would be helpful if you emailed me your library URL (without credentials), so I could try to connect to it myself.
oleg@radiokot.com.ua

**Comment by leosamuele221** [comment]
Probably it's specific to your setup.
I also have my photoprism hosted with https, my certificate is provided by let's encrypt and i have no problems

**Comment by ally9696** [comment]
ok, my setup uses

OS Openmediavault 6
Playit.gg for port forwarding.
Photoprism plugin via Openmediavault 
Virtual VM with Bridge network with seperate ip from host gateway.
Https dedicated to single uri and not wildcard SSL.

Using plain http won't have issues. Is it because of the ports is causing issues?
https://server4.upwaretech.in:4068
Admin[at]123.      Symbol @.  @Radiokot 
Http won't work because ssl is enabled, forced ssl not enabled.

Web HTTPS with ssl is working fine..

**Comment by ally9696** [comment]
![Screenshot_2023-05-24-23-00-12-05_54b4ff97b4165ae42c8f5e9bdd7817b2](https://github.com/Radiokot/photoprism-android-client/assets/59211330/05dfb31c-c265-479a-8565-05f38d48c03a)

**Comment by ippocratis** [comment]
Maybe this?
https://github.com/wallabag/android-app/issues/516#issuecomment-298114568

**Comment by ally9696** [comment]
I guess some hints are out, let me try

**Comment by ally9696** [comment]
![Screenshot_2023-05-25-00-51-41-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Radiokot/photoprism-android-client/assets/59211330/92f21a48-d21d-400e-ad46-613679f94ac9)

**Comment by ippocratis** [comment]
> ![Screenshot_2023-05-25-00-51-41-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Radiokot/photoprism-android-client/assets/59211330/92f21a48-d21d-400e-ad46-613679f94ac9)
> 

So most likely you have to fix intermediate certs for your reverse proxy

**Comment by ally9696** [comment]
I guess i need to add the intermediate SSL inside the cert where the header and footer ends to complete the trust chain..

**Comment by ally9696** [comment]
> 

Could this be a solution..

**Comment by ippocratis** [comment]
I'm not that technical ,
Cant help with that, sorry
As I said caddy does all the job for me

**Comment by Radiokot** [comment]
@ally9696 make sure in your server configuration you use the full chain file and not just the standalone certificate. For nginx it looks like this:
```ssl_certificate /etc/letsencrypt/live/radiokot.com.ua-0002/fullchain.pem; # managed by Certbot```
and the `fullchain.pem` file contains multiple certs one by one, like this:
```
-----BEGIN CERTIFICATE-----
MIIFwzCCBKugAwIBAgISBLw/vgERGMn8PYv32H4uVgJPMA0GCSqGSIb3DQEBCwUA
...xxx...
McnduECERMvk55VnhXoDzMsfz0htoUNWVAeaQoDov0dKx6Ez+Qkm
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
...xxx...
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
...xxx...
Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
-----END CERTIFICATE-----
```

**Comment by ally9696** [comment]
> I guess i need to add the intermediate SSL inside the cert where the header and footer ends to complete the trust chain..

Yes will try this out since i didn't configure the server with the full chain. Ill merge the certificate and wait for ssl cache to clear.

**Comment by ally9696** [comment]
During the login this error 
**"CertPathValidatorException: Trust anchor for certification path not Found."**

ROOT CA> INT CA > User Certificates into one Cert files. 
Fixed the issue and its no longer giving the login error.

**Comment by Radiokot** [comment]
Great! Thanks to everyone joined the investigation
