### ISSUE TITLE
Android TV user interface issues

### ISSUE THREAD

**Issue by Marcus-Schubert** [Radiokot/photoprism-android-client#60]
**What is wrong?**
When using the App on Android TV a few issues occur.

- The current photo is not marked when navigating with keyboard. Only the search bar is highlighted. Therefore it's nearly impossible to select the correct photo to open.
- Once a photo has been opened, it's not possible to navigate through the photos by clicking back and forth on the keyboard. Also it's not possible to reach the other UI elements (e.g. download). Only back button works.
- When entering the search it's impossible to enter text in the search bar (at least I haven't managed to do so). Selecting album and type works.
- It seems to be impossible to click on "reset" or "search" within the search as it can not be reached via keyboard. 

**To Reproduce**
1. Install apk via side loading to an Android TV device
2. Open the app

**Expected behavior**
Navigation is possible on Android TV devices via keyboard / remote control.

**Device (please complete the following information):**
 - Model: nVidia Shield Pro
 - Android version: Shield Android TV 9.1.1 (Android 11)

**Additional context**
Navigation only possible via remote control / keyboard

**Comment by Radiokot** [comment]
Marcus, thank you for the detailed description. Can you also clarify which keyboard is used for nVidia Shield and in what way? Is it a regular computer keyboard? Which keys do you use to move focus forward and backward?

**Comment by Marcus-Schubert** [comment]
I mainly used the remote control that comes with the Shield. You basically have a circular control where you can press up, down, left and right. I also ised a generic remote control (SofaBaton U1) with similar navigation and it resulted in the same behavior.

**Comment by Radiokot** [comment]
Okay, I'll try to fix navigation issues for the keyboard arrow buttons and hopefully it will have effect for remote controls. Thanks.

**Comment by Marcus-Schubert** [comment]
Awesome, thank you

**Comment by Radiokot** [comment]
Hey Marcus,
Please, check out the latest release https://github.com/Radiokot/photoprism-android-client/releases/tag/1.11.0(19)
I've implemented keyboard navigation for the gallery and media viewer screens. The search remains inaccessible without a mouse for now. 
Hope it works on your TV, I've only tested it in the emulator.

**Comment by Marcus-Schubert** [comment]
Hi @Radiokot, I just tested it on Android TV. Navigation in the gallery and media viewer works like a charm now.

Thank you

**Comment by Radiokot** [comment]
Glad to hear that, thank you for testing.
