### ISSUE TITLE
Translations needed for new strings 🇹🇷 🇬🇷 🇨🇳 🇮🇹

### ISSUE THREAD

**Issue by Radiokot** [Radiokot/photoprism-android-client#62]
I'm preparing the app to be featured on the PhotoPrism partners page and have added some clarifying elements to the app: the welcome screen and extra preference items. 
Please, help me translate the newly added strings to Turkish, Greek, Chinese and Italian🙏🏻  The most important are the welcome screen title and disclaimer.

## Welcome screen
<img width=300 src="https://github.com/Radiokot/photoprism-android-client/assets/5675681/485d4082-9106-40ae-8b13-d3d994e9a32d" />

Title:
```
Welcome to the gallery
```

Disclaimer:
```
Please note that this app is not an official PhotoPrism client.
It is maintained by Oleg\u00A0Koretsky (Radiokot) and has no relationship to the core team.\n\n
If something is wrong with the app, please leave a feedback on Google Play,
<a href="#issue">submit a bug report</a> or send a letter to 
<a href="mailto:oleg@radiokot.com.ua">oleg@radiokot.com.ua</a>.\n\n
Thank you.
```

## Preferences
<img width=300 src="https://github.com/Radiokot/photoprism-android-client/assets/5675681/cb69c67e-3521-454c-9f74-ed43cc56efaa" />

User guide:
```User guide```

Open-source licenses:
```Used open-source software```

Version info author and contributors:
```Oleg Koretsky and contributors from GitHub```

**Comment by Radiokot** [comment]
@cgcel @Baturax @leosamuele221 @ippocratis
Hi guys 👋🏻 Could you please translate the strings? You can simply drop a message here with the translation, or submit a new pull request.

**Comment by ippocratis** [comment]
I cant find the related strings on the main branch 
Are the changes public?

Anyway the Greek translation would be


**Title:**

Καλώς ήρθατε στην Gallery

**Disclaimer:**

`Λάβετε υπόψη ότι αυτή η εφαρμογή δεν είναι ένας επίσημος PhotoPrism client.
Συντηρείται απο τον Oleg\u00A0Koretsky (Radiokot) και δεν συσχετίζεται με την επίσημη ομάδα.\n\n
Αν κάτι πάει λάθος παρακαλώ αφήστε ενα σχόλιο στο Google Play,          
<a href="#issue">υποβάλετε μια αναφορά σφάλματος λ</a> ή στείλτε ενα μέιλ στο
<a href="mailto:oleg@radiokot.com.ua">oleg@radiokot.com.ua</a>.\n\n
Ευχαριστώ.`

**User guide:**
`Οδηγός χρήσης.`

**Open-source licenses:**
`Χρησιμοποιηθέντα προγράμματα ανοιχτού κώδικα.`

**Version info author and contributors:**
`Oleg Koretsky and συνεισφέροντες στο GitHub`

**Comment by ippocratis** [comment]
Congrats for the "partners" inclussion.
The app will get the attention it deserves..

**Comment by Radiokot** [comment]
> I cant find the related strings on the main branch Are the changes public?
They are in `main`, in order for them to appear in your fork, click "Sync fork" in your repository.
https://github.com/Radiokot/photoprism-android-client/blob/277bd7c6f064282837bc8d613fda10169dacf6ed/app/src/main/res/values/strings.xml#L111

Thank you for the translation!

**Comment by cgcel** [comment]
Ok, I will do it later

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
