### ISSUE TITLE
Too little time until SocketTimeoutException

### ISSUE THREAD

**Issue by adrian-klein** [Radiokot/photoprism-android-client#65]
**What is wrong?**
My Photoprim library contains about 175000 images and is on an old HDD in my NAS.
Login via browser takes roughly 25 seconds.
When trying to log in with the app, I get a SocketTimeoutException after 10 seconds, so I am unable to use the app.

**To Reproduce**
1. Have the library on a device with slow hardware
2. Have lots of images in the library
3. Try to log in via app

**Expected behavior**
I expect to be able to log in successfully

**Screenshots**
Browser:
![Screenshot_20230709-022341.png](https://github.com/Radiokot/photoprism-android-client/assets/60747383/db720fe6-ca14-4ce6-8de1-5cd538571898)

App:
![Screenshot_20230709-022416.png](https://github.com/Radiokot/photoprism-android-client/assets/60747383/5aa7ac6f-4f55-47ce-ac4c-cc847d33d84c)

**Device (please complete the following information):**
 - Model: Google Pixel 5
 - Android version: 13

**Additional context**
I understand that for most people a timeout of 10s is enough since oftentimes it means you're really not able to reach the configured endpoint. But maybe there is a different way of recognizing if it's reachable so that a longer socket timeout could be used.

**Comment by Radiokot** [comment]
Hi Adrian.

I agree that 10 seconds is not enough, considering PhotoPrism is usually being run on low-power home servers. The read/write timeout will be increased. Subscribe to the repository and you'll get a notification once the new release is available.

Indeed, PhotoPrism is an amazing software. It works slowly, but surely, even on such slow devices like home NAS.

**Comment by ippocratis** [comment]
Some times I have to re-enter the server url e.g. adding or removing a trailing slash

**Comment by Radiokot** [comment]
Good evening, Adrian. 
Please, check out the latest release where the timeout is increased:
https://github.com/Radiokot/photoprism-android-client/releases/tag/1.14.0(22)

**Comment by adrian-klein** [comment]
Sorry for the late response! 
Yes it is indeed working for me now.
Thanks a lot for the quick change!
