### ISSUE TITLE
Higher resolution photos (not downscaled) never load

### ISSUE THREAD

**Issue by linosgian** [Radiokot/photoprism-android-client#71]
**What is wrong?**
On both my android phones and the Android TV, high resolution photos never load. Sometimes (especially on the Android TV) the app crashes. This is not an issue for the official photoprism PWA app.

An example of such a case is a photo taken with my phone:
JPEG 8192x6144, 6.8 MBs

When I enable downscaling, things work fine for some of the photos, others continue to fail loading.

**To Reproduce**
1. Browse any photo that has high resolution.

**Expected behavior**
All photos should -eventually- load (up to a reasonable size/resolution)

**Screenshots**

**Device (please complete the following information):**
 - Model: TCL 55EP660
 - Android version: 9

 - Model: OnePlus Nord 2
 - Android version: 13

**Comment by Radiokot** [comment]
Hi. Thank you for the report, I will check it.

**Comment by linosgian** [comment]
Following the official docs [here](https://docs.photoprism.app/user-guide/settings/advanced/):

```
To view original images, enable Dynamic Previews, and configure Dynamic Size Limit and Static Size Limit to a small value like 720. When viewing images exceeding that limit, the original files will be displayed.
```

**Comment by linosgian** [comment]
Playing around with the settings a little bit, it looks like when photos are downscaled the issue is less likely to happen, but it seems like a general performance issue. For instance, if I swipe through my library too fast, the issue occurs even with downscaling (too many downloads happening at once potentially ?). When the original photo is served, trying to view even one image, the app crashes

**Comment by Radiokot** [comment]
There was an obvious issue in the code: downscaling was disabled to improve zoom capabilities, but I didn't know it was possible to get a file from PhotoPrism that exceeds the requested preview size. 
The fix will be included in the next release.

**Comment by Radiokot** [comment]
The fix is included to the [latest release](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.16.1(26))

**Comment by linosgian** [comment]
I've updated and tested, everything works flawlessly on my phone, thanks!
