### ISSUE TITLE
Cannot exit selection mode

### ISSUE THREAD

**Issue by jvadair** [Radiokot/photoprism-android-client#75]
**What is wrong?**
Once a photo has been selected, you cannot exit selection mode without closing the application.

**To Reproduce**
1. Open the application
2. Hold tap on a photo
3. Try to click the 'X' button on the bottom

**Expected behavior**
The application should exit selection mode

**Screenshots**
![IMG_20230805_141813.jpg](https://github.com/Radiokot/photoprism-android-client/assets/58600250/8f8f97d4-7470-43c4-8121-a49e40960b52)

**Device (please complete the following information):**
 - Model: OnePlus Nord N20 5G
 - Android version: 12
- System language: Italian (but I am a native English speaker)
- Location: USA

**Additional context**
I installed the latest version from F-droid today.

**Comment by Radiokot** [comment]
Hi James. You can exit the mode by making the "Back" gesture. But I agree that the "X" button behavior is unintuitive and should be changed.

**Comment by jvadair** [comment]
Thanks for fixing this!
To clarify, does a long press exit the selection mode or clear the selection?

Personally, I feel it would be more intuitive to clear and exit the selection when the button is pressed, as there is no reason to remain in selection mode if there are no selections, nor is there any reason to keep things selected when not in selection mode.

**Comment by Radiokot** [comment]
Clicking the "X" button will exit the selection mode, if the selection mode is started by a long press on gallery item. There is another way to get into the selection mode – when the gallery is started by some other app to pick content. In this case "X" works as before.

**Comment by Radiokot** [comment]
The change is included to the [latest release](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.16.1(26))
