### ISSUE TITLE
Live Photos always play the video portion and don't show the actual photo

### ISSUE THREAD

**Issue by MEGAMENE** [Radiokot/photoprism-android-client#77]
**What is wrong?**
When I open a Live Photo on the app it starts playing the video automatically, I can't find any way to stop the video and just see the photo.

**To Reproduce**
1. Open a Live Photo in the app.

**Expected behavior**
There should be a button to stop the video and just show the photo, maybe by pressing on the video too.

**Screenshots**

**Device (please complete the following information):**
 - Model: Google Pixel 6
 - Android version: 13

**Comment by Radiokot** [comment]
Hi. What's bad about in it? Isn't the photo part of a PhotoPrism live photo just a first frame of the video?

**Comment by MEGAMENE** [comment]
> Hi. What's bad about that? Isn't the photo part of a PhotoPrism live photo just a first frame of the video?

Based on my experience from Samsung Motion Photos and Pixel Motion Photos the motion video can be before, during or after the actual photo.
The photo itself is also usually higher quality than the video and with a different resolution/aspect ratio.
I upload the jpg and mp4 files separately into PhotoPrism with the same name, and PhotoPrism imports both files as a Live Photo with the jpg as the primary file.

**Comment by Radiokot** [comment]
Please, send me an example file(s). My email is oleg@radiokot.com.ua

**Comment by MEGAMENE** [comment]
> oleg@radiokot.com.ua

I just send an email.

**Comment by Radiokot** [comment]
Thank you, I'll see what can be done.

**Comment by Radiokot** [comment]
I've never used live photos on my Samsung, as they come out shaking and not aesthetic at all. But yesterday I took some photos of my cat with an iPad and damn, they look amazing and played so naturally and smooth when browsing through the iOS gallery. iOS live photos have a kind of magical feeling for me.
I'll try to make a beautiful live photo viewer in the gallery, would be great if I could re-create the iOS experience.

**Comment by Radiokot** [comment]
Check out the latest release:
https://github.com/Radiokot/photoprism-android-client/releases/tag/1.17.0(27)

JPEG+MP4 batches should be shown as end-fade live photos.

**Comment by MEGAMENE** [comment]
> Check out the latest release: https://github.com/Radiokot/photoprism-android-client/releases/tag/1.17.0(27)
> 
> JPEG+MP4 batches should be shown as end-fade live photos.

I just tried the new version and the functionality is working well but there's some bugs I found.
First the Live Photos have no sound, when playing them on the PhotoPrism website the sound works.
Secondly some of the videos appear shorter on the app than on the PhotoPrism website.

**Comment by Radiokot** [comment]
It is supposed to play like this in the gallery.
Live photo looks beautiful when it is shown as a small part of the video without sound fading into the high-quality still image. You can see the full video with sound by clicking "Open in".
