### ISSUE TITLE
donate link on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [Radiokot/photoprism-android-client#79]
@Radiokot 
* **without your explicit consent** donate link ```https://radiokot.com.ua/tip```  given in https://github.com/Radiokot/photoprism-android-client/discussions/21 was replaced by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/ua.com.radiokot.photoprism.yml)
* donate link updated in fdroid metadata will create link on fdroid client
* should i remove it?

**Comment by Radiokot** [comment]
Hello again 👋
This is fine, thank you for updating the link. Do not remove it.
