### ISSUE TITLE
fatal exceptions 

### ISSUE THREAD

**Issue by ippocratis** [Radiokot/photoprism-android-client#8]
For starters thanks so much for the app
I'm a selfhoster and mostly viewing photos on my phone
so
I was very excited when I saw an active android client for the most popular (and probably most stable)  photo managment software photoprism.
Unfortunately the app crashes on my device 

OS: android 13 , sparkOS (custom rom),  unlocked bootloader,  rooted

Photoprism build: 221118-e58fee0fb

Grabed some logs 
App Logins and open fine
but crashes as long as I try to scroll in the timeline

[logcat_scroll_timeline.txt](https://github.com/Radiokot/photoprism-android-client/files/11140794/logcat_scroll_timeline.txt)

If I tap on one of the firsy images without scrolling it opens and I can swipe left to the other images for some time before it crashes
[logcat_image_view-swipe.txt](https://github.com/Radiokot/photoprism-android-client/files/11140791/logcat_image_view-swipe.txt)

Thanks and keep up

**Comment by Radiokot** [comment]
I think I've found the cause and fixed it. Please, check this debug version: https://anonfiles.com/F2v6Rci0z1/app_debug_apk
**Notice: the debug version logs all HTTP requests. If the crash is still there, do not attach the whole logcat output here. Drop it to my e-mail oleg@radiokot.com.ua**

**Comment by ippocratis** [comment]
Maybe something to do with fastscrollview?
It apears a lot in the error log
Also
Downgraded to 1.1.0 and it does not crash

**Comment by Radiokot** [comment]
So the debug version with the apparent fix didn't fixed the crash? Please, send me fastscroll-related records from the log. For now, I can't reproduce the crash.

**Comment by ippocratis** [comment]
> I think I've found the cause and fixed it. Please, check this debug version: https://anonfiles.com/F2v6Rci0z1/app_debug_apk
> **Notice: the debug version logs all HTTP requests. If the crash is still there, do not attach the whole logcat output here. Drop it to my e-mail oleg@radiokot.com.ua**

Sorry
I urged to post my findings without seeing your comments
Installed the debug version
It works fine
not crashing
(I was refering to my the logs from my initial message about fastscrollview)
Thanks
