### ISSUE TITLE
refresh on long pull

### ISSUE THREAD

**Issue by rickysarraf** [Radiokot/photoprism-android-client#80]
**What is wrong?**
On long pull from the top, the app does not talk back to the server to get a refreshed list of items. The list that is rendered is generated on app start-up. After that, no matter how many times I pull down, it doesn't refresh.

**To Reproduce**
1. Open app
2. Get an initial list of items
3. Add items on the remote server
4. Index items on remote server
5. Refresh on this app

**Expected behavior**
Newly indexed items should reflect

**Device (please complete the following information):**
 - Model: Google Pixel 7
 - Android version: 13

**Additional context**
Take a look at the PWA app. It does refresh on pull down.

**Comment by Radiokot** [comment]
I've removed the "bug" label because this feature is not broken, it just isn't there 🙂
I'll consider adding it.

**Comment by Radiokot** [comment]
Hi. It's been added to the latest release: https://github.com/Radiokot/photoprism-android-client/releases/tag/1.18.0(28)
