### ISSUE TITLE
PhotoPrism Gallery does not reach library when on the same network as the library

### ISSUE THREAD

**Issue by finngar** [Radiokot/photoprism-android-client#81]
Hello, I have encountered a issue in the PhotoPrism Gallery v1.17.0 where if you are on the same network as as the PhotoPrism server, the app will not be able to reach the library.

My set up:
I have PhotoPrism docker running on a unraid server on my home network. The URL for PhotoPrism is set to the default "http://admin@192.168.x.xxx:2342/originals/"
I set up a SWAG reverse proxy through Duck DNS. The URL is "customURL.duckdns.org".
I have successfully linked those in unraid, so now when use my phone or computer browser and I go to "https://customURL.duckdns.org" PhotoPrism loads. I can access Photoprism this way both on my network and off my network.
I have the PhotoPrism Gallery app library root URL set to "customURL.duckdns.org".

The app is able to connect to the library when on any other network than my home network (the one that hosts PhotoPrism).
Once I turn on wifi at home the app says it can not connect to the library. However I am still able to reach PhotoPrism's GUI via the web browser on while on the same network on the same phone.

Admittedly, I am not the most adept at networking or setting up reverse proxies. So the issue could be on my end. However it is odd to me that while the app can not reach the library when on my wifi the mobile browser can.

**Comment by Radiokot** [comment]
Hi. What does the app say in the error message?

**Comment by finngar** [comment]
The app tries to load the library for 20-30 seconds, then says "Library is not accessible. Check connection and try again."

**Comment by Radiokot** [comment]
I think, enabling "NAT Loopback" option in your router WAN/LAN configuration might help.

**Comment by finngar** [comment]
I had to google NAT Loopback and I think you are correct, thank you!
It seems until I get a router that supports that the workaround it to use my mobile data.
Thank you again for the help.
