### ISSUE TITLE
Can't connect to my library

### ISSUE THREAD

**Issue by eratnik** [Radiokot/photoprism-android-client#86]
**What is wrong?**
Error "Library is not accessible: HTTP 404" when i try to connect to my library. My URL is correct, I can connect to this in browser.

**To Reproduce**
1. Go to my library's URL
2. Enter my login and password
3. See error

**Screenshots**
![Screenshot_20230920-131046~2.png](https://github.com/Radiokot/photoprism-android-client/assets/23414787/55f65143-6fd0-4e45-87c7-42dcb4eb800e)

**Device:**
 - Model: [e.g. Pixel 6a]
 - Android version: [e.g. 13]
 - App version 1.18.0

**Additional context**
Router keenetic Kn-1010, I use keendns.

**Comment by Radiokot** [comment]
Hi. I assume Keenetic DNS does a redirect, requires an authentication/captcha or in some other way prevents connection to the PhotoPrism server API. You can send me your URL without credentials by email, so I can check what exactly is wrong. oleg@radiokot.com.ua
