### ISSUE TITLE
Video-format is hardcoded, should be dynamic

### ISSUE THREAD

**Issue by dfoxg** [Radiokot/photoprism-android-client#87]
## What is wrong?
Photoprism allows the specify the video format in which the video should be streamed/downloaded: https://github.com/photoprism/photoprism/blob/ce4cb6bd47cc/internal/api/video.go#L25

At the moment, in photoprism-android-client the video is hardcoded to avc: https://github.com/Radiokot/photoprism-android-client/blob/main/app/src/main/java/ua/com/radiokot/photoprism/features/gallery/logic/PhotoPrismPreviewUrlFactory.kt#L43

It should be great if the requested video format should be dynamic.

### Background-Info:
I´m running `photoprism convert` in a cronjob to transcode all my videos so that the videos can get streamed instantly. The `convert` command transcode the videos in a lower bitrate so that my device can display these also in low-network-situations. 

That works fine with the photoprism-web-ui. But when using the mobile app, photoprism triggers a transcode on the fly even for example the `hevc` format already exists as a transcoded video, because at the moment `avc` is getting requested.

The codec can be getted from the rest api:
```
[
  {
    "ID": "21866-40001",
    ....
    "Files": [
      {
        "UID": "fs194zdqar778v1f",
        "PhotoUID": "ps194zb1ttfvybb0",
        ...
        "FileType": "jpg",
        "MediaType": "image",
        "Mime": "image/jpeg"
      },
      {
        "UID": "fs194zb2mn8quou0",
        "PhotoUID": "ps194zb1ttfvybb0",
        ....
        "Codec": "hvc1",  # here is the codec. hvc1 is hevc in the rest api, avc1 is avc (the current default)
        "FileType": "mp4",
        "MediaType": "video",
        "Mime": "video/mp4",
        ....
      }
    ]
  },
```

**Comment by Radiokot** [comment]
Did you make some changes to the web client / server configuration to make it use HEVC for previews?

**Comment by dfoxg** [comment]
Nope, I just decreased the ffmpeg_bitrate and enabled hardware encoding (intel).

Just the be sure, because you have written preview: it's not affecting the preview, it's when clicking on a video to start it.

I'm playing with big HDR videos at the moment (80mbits bitrate), maybe that could be the trigger.

**Comment by Radiokot** [comment]
The gallery does not show originals. Whatever the original content is (RAW, JPEG, HEIF, HEVC, SVG, etc.), the gallery requests resized JPEG previews for still images and AVC MP4 for videos and animations. You can open original or sidecar file of a particular item from the viewer, but it will be fully  downloaded then.
For me, it doesn't seem obvious that the HEVC preview needs to be loaded instead of AVC if there is a HEVC video among the item files. I tried uploading HEVC video to both my home server and the public demo, and both play it as AVC. If I manually change /avc to /hevc in the end of the preview URL, I get sound-only playback.

**Comment by Radiokot** [comment]
By preview I mean a transcoded, compressed and resized video file which is prepared by PhotoPrism for the original content.

**Comment by dfoxg** [comment]
Hmm that's weird. When I'm scrolling through the web UI, ~20% of the videos are getting requested as HEVC, the rest are AVC.

Maybe it depends on the encoder (intel hardware in my case) or the source videos (h.256 with 10bit HDR). 

In the case your getting the sound-only "video" - what was the codec type which you were getting over the rest API?

If you want, I can send you a original HDR h.256 file to reproduce it.

Steps to reproduce the double transcoding:
1. Upload the h.256 file
2. Open the video in the web-ui (a transcoding is getting triggered)
3. Verify: Delete your Browser cache and open the same video again - now no transcode should be triggered again
4. Open the video over the app (in my case another transcoding is triggert)

You can tail the logs of the docker container to check if a transcoding is happening.

**Comment by Radiokot** [comment]
Thanks for extra details, I think getting a sample file could help me investigate the case. Please, send it to me by email oleg@radiokot.com.ua

**Comment by Radiokot** [comment]
In my case, the original video was MP4 HVC1.

**Comment by dfoxg** [comment]
I just send you the file. Thanks!

**Comment by Radiokot** [comment]
Can I upload it to the public demo?

**Comment by dfoxg** [comment]
Yes!

**Comment by dfoxg** [comment]
Somehow I can't reproduce if anymore. If you can't reproduce it either, let's close the issue.

**Comment by Radiokot** [comment]
So I tried uploading your sample file to both my home server and the public demo, and both play it as AVC. I can, however, open the AVC preview URL and change the format to HEVC – while my browser can't properly play such a file, if I download it, it is played well. 
I tried changing the format for video previews in the gallery to HEVC. For my home server, it slowed down the loading speed. Also animations from the demo environment, like the planet gif, are played incorrectly when using HEVC. But I've made a clone build for you, so you can test it with your environment: https://send.bitwarden.com/#W4sjtT5ObE-perCGAKNUeQ/dxC5JZGCAXR9-fEWg7Foxg

**Comment by dfoxg** [comment]
Thanks a lot!!

**Comment by Radiokot** [comment]
I've been contacted by another user who has HEVC videos in his library with disabled FFmpeg and expects them to be directly streamed without transcoding to AVC, as does the web app in his case. So I think I should implement the same video format selection as in the web app and so it will be dynamic.

**Comment by Radiokot** [comment]
I managed to reproduce HEVC playback in the web app through uploading HEVC (hvc1) video from my Samsung to the public demo and then viewing it in mobile browser which supports HEVC unlike my desktop browser. For some reason, the rotation is wrong, but if I force the same file to be played as HEVC in the gallery, it does it just fine.
<img src="https://github.com/Radiokot/photoprism-android-client/assets/5675681/973169ac-2976-4740-8b16-e1af1c3a45eb" width=300 />

**Comment by MEGAMENE** [comment]
I'm having some problems getting this to work with videos from a GoPro Hero 11. It still tries to transcode it.

**Comment by Radiokot** [comment]
@MEGAMENE could you send me a sample file? Please, do not select anything personal so I could upload it to the public demo.

**Comment by MEGAMENE** [comment]
> @MEGAMENE could you send me a sample file? Please, do not select anything personal so I could upload it to the public demo.

I sent a sample to the same email as last time.

**Comment by Kh3nsu** [comment]
I also got a hevc video .mp4 file which is not playing in the gallery app but just fine in the web view. It is from my dashcam.
![image](https://github.com/Radiokot/photoprism-android-client/assets/17033125/42e5e373-0d67-41b0-8ce5-8ab9fe067ef7)

**Comment by Radiokot** [comment]
The fix will be released soon.

**Comment by Radiokot** [comment]
@MEGAMENE @Kh3nsu the fix for large resolution videos is in the [1.20.2 release](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.20.2(32))

**Comment by Kh3nsu** [comment]
> @MEGAMENE @Kh3nsu the fix for large resolution videos is in the [1.20.2 release](https://github.com/Radiokot/photoprism-android-client/releases/tag/1.20.2(32))

Just downloaded the latest Version but I sadly still can't view the dashcam video. The screen just stays black. Do I have to do anything?

**Comment by Radiokot** [comment]
@Kh3nsu please, try downloading the HEVC file to your phone and playing it in the standard gallery.

**Comment by Kh3nsu** [comment]
> @Kh3nsu please, try downloading the HEVC file to your phone and playing it in the standard gallery.

Yeah that works as well. Already tried.

**Comment by Radiokot** [comment]
@Kh3nsu please, send me the sample to oleg@radiokot.com.ua

**Comment by Kh3nsu** [comment]
> @Kh3nsu please, send me the sample to [oleg@radiokot.com.ua](mailto:oleg@radiokot.com.ua)

Sent
