### ISSUE TITLE
Mutual tls client certificate [feature request]

### ISSUE THREAD

**Issue by ippocratis** [Radiokot/photoprism-android-client#9]
I am reverse proxying photoprism with caddy and i have configured it to use mutual tls with selected services it proxies adding the corenspodimg directive to them

I have installed the p12 client cert to the amdroid store

With the PWA it was easy
since it opens in a browser and the browser picks the client cert from the device cert store 

Mutual tls will add an extra security layer to the app

Example app using it
https://github.com/bitfireAT/davx5-ose/commit/3689df1385b31343ff537334bd3d71cb7f074959

Thanks
keep up

**Comment by Radiokot** [comment]
Thanks for the idea. I agree that it is important, as mTLS is often used for self-hosted solutions.
Could you please advise me, does it also mean that the app need to trust unknown CAs? Right now, the app does not trust unknown CAs and self-signed certificates unless they are manually added to the Android user trusted CAs.

**Comment by ippocratis** [comment]
> Thanks for the idea. I agree that it is important, as mTLS is often used for self-hosted solutions.
> Could you please advise me, does it also mean that the app need to trust unknown CAs? Right now, the app does not trust unknown CAs and self-signed certificates unless they are manually added to the Android user trusted CAs.

I'm not sure but I don't think it is needed to bother with the sever CA certs
In the implementations I've seen the user all it needs to do is select the client cert throughout  the app with file picker and add the cert password

Davx5
![Screenshot_20230404-201308_DAVx⁵.png](https://user-images.githubusercontent.com/52239579/229867645-da2bafc5-6877-49f3-889e-24380ec9381a.png)

Foldersync
![Screenshot_20230404-201409_FolderSync Pro.png](https://user-images.githubusercontent.com/52239579/229867859-a6126441-132b-4847-aea8-1e75b45effde.png)

Total commamder
![Screenshot_20230404-201501_TotalCmd-WebDAV (WEB Folders).png](https://user-images.githubusercontent.com/52239579/229868060-ad557bfc-6c2a-491c-b1ed-e022c53fd597.png)

**Comment by Radiokot** [comment]
Great, thanks for the examples!

**Comment by ippocratis** [comment]
Moving this to discussion as its more appropriate
